=== Digital-Twin-Operational-Platform/DTHiveOntology/mongodb_schema/structure-data.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://github.com/Digital-Twin-Operational-Platform/DTHiveOntology/structure-data.json",
    "bsonType": "object",
    "title": "RAF T1A Hawk Schema: base structure",
    "description": "a JSON schema for time-history based data for DTHive/DigiTwin",
    "required": [
        "version",
        "testName",
        "timeStamp"
    ],
    "properties": {
        "version": {
            "bsonType": "string",
            "title": "version number",
            "description": "the version of the schema that the document is compliant to",
            "enum": [
                "1.0.0"
            ]
        },
        "testName": {
            "bsonType": "string",
            "title": "test name",
            "description": "the unique test name for experimental testing",
            "minLength": 1
        },
        "timeStamp": {
            "bsonType": "long",
            "title": "UTC date",
            "description": "the timestamp of when the data was recorded, stored in nanoseconds since UNIX epoch"
        },
        "channelData": {
            "$ref": "channel-data.json"
        },
        "testType": {
            "$ref": "testtype-metadata.json"
        },
        "sensorData": {
            "$ref": "sensordata-metadata.json"
        }
    }
}

=== Digital-Twin-Operational-Platform/DTHiveOntology/mongodb_schema/testingDocuments/DesiredDocument_t2.json
{
    "version": "1.0.0",
    "testName": "TestJSON",
    "timeStamp": "1653051620",
    "channelData": [
        {
            "name": "Sensor1",
            "type": "accelerometer",
            "value": 1.56,
            "units": "g"
        },
        {
            "name": "Sensor2",
            "type": "accelerometer",
            "value": 6.34,
            "units": "g"
        },
        {
            "name": "Force1",
            "type": "load",
            "value": 10.5,
            "units": "N"
        }
    ]
}

=== Digital-Twin-Operational-Platform/DTHiveOntology/mongodb_schema/testingDocuments/DesiredDocument_o2.json
{
    "version": "1.0.0",
    "testName": "TestJSON",
    "timeStamp": "1653051619",
    "testType": {
        "excitation": {
            "type": "sineSwept",
            "outputLevel": 0.4,
            "parameters": {
                "frequency": {
                    "min": 3.0,
                    "max": 30.0,
                    "units": "Hz"
                },
                "sweep": {
                    "direction": "up",
                    "rate": 0.1,
                    "rateUnits": "Hz/s",
                    "type": "linear"
                }
            }
        },
        "amplification": {
            "value": 50.0,
            "units": "percentage"
        },
        "bandwidth": {
            "value": 30.0,
            "units": "Hz"
        },
        "spectralLines": 512,
        "averages": 3,
        "control": "openLoop",
        "repetition": 2,
        "testingNotes": "Testing Notes from Experimentalist",
        "additonalMass": [
            {
                "value": 1.2,
                "units": "Kg",
                "location": {
                    "X": 0,
                    "Y": 2.3,
                    "Z": 1.8,
                    "units": "m"
                }
            },
            {
                "value": 0.5,
                "units": "Kg",
                "location": {
                    "X": 0.6,
                    "Y": 1.3,
                    "Z": 6.8,
                    "units": "m"
                }
            }
        ]
    },
    "sensorData": [
        {
            "name": "Sensor1",
            "model": "352C04",
            "assetNumber": "56C123",
            "manufacturer": "PCB",
            "calibration": {
                "gain": 10.0,
                "units": "mV/g",
                "date": "8 June 2012"
            },
            "location": {
                "X": 1.9,
                "Y": 1.1,
                "Z": -1.8,
                "units": "m"
            }
        },
        {
            "name": "Sensor2",
            "model": "352C04",
            "assetNumber": "56C098",
            "manufacturer": "PCB",
            "calibration": {
                "gain": 10.0,
                "units": "mV/g",
                "date": "8 June 2012"
            },
            "location": {
                "X": 1.1,
                "Y": 1.1,
                "Z": 1.8,
                "units": "m"
            }
        },
        {
            "name": "Force1",
            "model": "1204-12A",
            "assetNumber": "12B893",
            "manufacturer": "PCB",
            "calibration": {
                "gain": 4.0,
                "units": "mV/N",
                "date": "8 June 2012"
            },
            "location": {
                "X": 0,
                "Y": 0,
                "Z": 0,
                "units": "m"
            }
        }
    ]
}
